# .github/workflows/dynamic.yml

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MODEL: text-davinci-003
        TEMPERATURE: 0.7
        MAX_TOKENS: 3600

    - name: Check code formatting with Black
      run: |
        black --check .
