# .github/workflows/dynamic.yml

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install
        pip install -e .[dev]

    - name: Install dependencies from requirements.txt
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Run flake8
      run: |
        flake8

    - name: Run pytest
      run: |
        pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_MODEL: text-davinci-003
        OPENAI_MODEL_GPT4: gpt-4
        ANTHROPIC_MODEL: claude-instant-v1
        TEMPERATURE: 0.7
        MAX_TOKENS: 3600

    - name: OSSF Scorecard action
      uses: ossf/scorecard-action@v2.2.0