# .github/workflows/merge-main.yml

name: Python application

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11.0"] 

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ."[dev]"

    - name: Check code formatting with Black
      run: |
        black --check .

    - name: Run flake8
      run: |
        flake8

    - name: Run Tox
      run: |
        tox
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_MODEL: text-davinci-003
        OPENAI_MODEL_GPT4: gpt-4
        ANTHROPIC_MODEL: claude-instant-v1
        TEMPERATURE: 0.7
        MAX_TOKENS: 3600
